# Generated by Django 4.2.5 on 2023-09-21 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActReturning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('return_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=50)),
                ('title_origin', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('instance', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=15)),
                ('publishing', models.DateField(blank=True)),
                ('registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('pages', models.IntegerField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(blank=True, max_length=40)),
                ('passport_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('residence', models.TextField(blank=True)),
                ('active_act_issuing', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('act_returning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.actreturning')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.copy')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.violation')),
            ],
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to='image')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='librarian.genre'),
        ),
        migrations.CreateModel(
            name='AuthorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_photo', models.ImageField(upload_to='image')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.AddField(
            model_name='actreturning',
            name='copies',
            field=models.ManyToManyField(to='librarian.copy'),
        ),
        migrations.AddField(
            model_name='actreturning',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.reader'),
        ),
        migrations.CreateModel(
            name='ActIssuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('issuing_date', models.DateField()),
                ('return_date', models.DateField()),
                ('tentative_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('copies', models.ManyToManyField(to='librarian.copy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.reader')),
            ],
        ),
    ]
